spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlindev?useSSL=false&serverTimezone=UTC
    username: kotlin
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

server.compression.enabled: false
